name: active_ecommerce_cms_demo_app
description: "A new Flutter project."
publish_to: "none"
version: 3.4.4+13


environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  clipboard: ^0.1.3
  connectivity_plus:
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  dotted_line: ^3.2.3
  dropdown_search: ^6.0.2
  expandable: ^5.0.1
  file_picker: ^10.2.0
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_credit_card: ^4.1.0
  flutter_downloader: ^1.12.0
  flutter_facebook_auth: ^7.0.1
  flutter_html: ^3.0.0-beta.1
  flutter_local_notifications: ^18.0.1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.8
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  google_maps_place_picker_mb: ^3.1.2
  google_sign_in: ^7.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.5
  json_annotation: ^4.1.0
  logging: ^1.0.2
  one_context: ^4.0.0
  package_info_plus: ^4.0.2
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  phonepe_payment_sdk: ^2.0.3
  photo_view: ^0.15.0
  provider: ^6.0.0
  rename: ^3.0.2
  route_transitions: ^2.0.1
  share_plus: ^10.0.2
  shared_preferences: ^2.0.8
  shared_value: ^3.0.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^6.1.1
  timeline_list: ^0.0.3
  timeline_tile: ^2.0.0
  url_launcher: ^6.0.12
  validators: ^3.0.0
  webview_flutter: ^4.13.0
  path: ^1.9.0
dependency_overrides:
  google_api_headers: ^4.6.2
  package_info_plus: ^4.0.2
  webview_flutter_wkwebview: 3.15.0
dev_dependencies:
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.13
  json_serializable: ^6.2.0
  flutter_svg:
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http:
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-icon.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/htmls/
    - assets/fonts/
    - dummy_assets/
  fonts:
    - family: PublicSansSerif
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
        - asset: assets/fonts/PublicSans-Bold.ttf
        - asset: assets/fonts/PublicSans-Medium.ttf
        - asset: assets/fonts/PublicSans-SemiBold.ttf
        - asset: assets/fonts/PublicSans-Italic.ttf
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

#flutter pub run intl_utils:generate
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/l10n
  output_dir: lib/l10n
